[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Paksa penanganan header untuk mencegah 304 (Cache)
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"